#ifndef SINGLEPLAYER_CONSTANTS_HPP_INCLUDED
#define SINGLEPLAYER_CONSTANTS_HPP_INCLUDED
//--------------------------------------------------


const int MAX_DIFFICULTY_0_SCORE = 1000;
const int MAX_DIFFICULTY_1_SCORE = 2000;



const double DIFFICULTY_0_MIN_PLATFORM_GAP = 60;
const double DIFFICULTY_1_MIN_PLATFORM_GAP = 90;
const double DIFFICULTY_2_MIN_PLATFORM_GAP = 120;

const double DIFFICULTY_0_MAX_PLATFORM_GAP = 100;
const double DIFFICULTY_1_MAX_PLATFORM_GAP = 150;
const double DIFFICULTY_2_MAX_PLATFORM_GAP = 200;


const double DIFFICULTY_0_DEFAULT_PLATFORM_CHANCE = 0.9;
const double DIFFICULTY_0_MOVING_PLATFORM_CHANCE  = 0.1;

const double DIFFICULTY_1_DEFAULT_PLATFORM_CHANCE = 0.7;
const double DIFFICULTY_1_MOVING_PLATFORM_CHANCE  = 0.3;

const double DIFFICULTY_2_DEFAULT_PLATFORM_CHANCE = 0.7;
const double DIFFICULTY_2_MOVING_PLATFORM_CHANCE  = 0.3;


//--------------------------------------------------
#endif